const fs = require('fs');

const content = 'This was generated by a GitHub action. (script.js) \nThis is on line 2.';

fs.writeFile('test.txt', content, err => {
    if (err) {
        console.error(err);
    }
    console.log("This is from script.js")
    // file written successfully
});