const fs = require('fs');

const content = 'This was generated by a GitHub action. (script.js) \nThis is on line 2. \nVersion: ' + process.env['npm_package_version'];

fs.writeFile('test.txt', content, err => {
    if (err) {
        console.error(err);
    }
    console.log("text.txt file contents:")
    console.log("==========")
    console.log(content)
    console.log("==========")
    // file written successfully
});