const fs = require('fs');

const content = 'This was generated by a GitHub action. (script.js) \n This is on line 2.';

fs.writeFile('test.txt', content, err => {
    if (err) {
        console.error(err);
    }
    // file written successfully
});