name: Auto-triggered workflow
on:
  workflow_dispatch: 
    inputs:
      test: 
        required: true
        defalut: "The default message."
  push:
    branches:
      - main
jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: run github-script
      uses: actions/github-script@v1
      with:
        script: |
          const core = require('@actions/core');
          var msg = core.getInput("test", { required: false })
          core.notice(msg)