name: Auto-triggered workflow
on:
  workflow_dispatch: 
  push:
    branches:
      - main
jobs:
  functions-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: define and run the function
      run: |
        getFromAPI() {
          v = 'Hello'
          v += " World"
          echo $v
        }
        getFromAPI