name: Auto-triggered workflow
on:
  workflow_dispatch: 
    inputs:
      input: 
        required: true
  push:
    branches:
      - main
jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: conditional test
      if: "startsWith(github.event.head_commit.message, 'WIP')"
      run: |
        echo "message started with WIP"
    - name: conditional test 2
      if: "!startsWith(github.event.head_commit.message, 'WIP')"
      run: |
        echo "message does not start with WIP"