name: Auto-triggered workflow
on:
  workflow_dispatch: 
  push:
    branches:
      - main
jobs:
  functions-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: define and run the function
      run: |
        getFromAPI() {
          curl https://api.github.com/repos/AdamRaichu/actions-test/contents/.github/workflows
          curl https://api.github.com/repos/adamraichu/actions-test/commits
        }
        getFromAPI