# This is a basic workflow that is manually triggered

name: Auto-triggered workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch: 
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  getInfo:
    runs-on: ubuntu-latest

    steps:  
    - name: Get repo info
      run: curl https://api.github.com/repos/AdamRaichu/actions-test/contents/.github/workflows
      run: curl https://api.github.com/repos/adamraichu/actions-test/commits