# This is a basic workflow that is manually triggered

name: Auto-triggered workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch: 
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  about-repo:
    runs-on: ubuntu-latest

    steps:  
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Get repository info
    name: List files in the repository
    run: |
      ls ${{ github.workspace }}