# This is a basic workflow that is manually triggered

name: Manually-triggered workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  get-repo-info:
    runs-on: ubuntu-latest

    steps:  
    - name: Get `workflows` contents info
      run: curl https://api.github.com/repos/AdamRaichu/actions-test/contents/.github/workflows
    - name: Get commits
      run: curl https://api.github.com/repos/adamraichu/actions-test/commits
  update-lastUpdated_txt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          date > lastUpdated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "pushed to lastUpdated"
          git push
  function-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          Hello() {
            echo "Hello World"
          }
          Hello